#!/bin/bash

if [[ "$XDG_SESSION_TYPE" != "wayland" ]]; then
echo "This script can only be executed in a Wayland environment."
exit 1
fi

if ! command -v dbus-daemon &> /dev/null; then
echo "#################################################################"
echo "ERROR: This script requires DBus to be executed."
echo "Make sure you have DBus installed on your system."
echo "DBus is required for inter-process communication."
echo "#################################################################"
exit 1
fi

clear
echo "#################################################################"
echo "opti-gnome-wayland-installer: june 2023"
echo "#################################################################"
echo "  ██████  ███    ██  ██████  ███    ███ ███████ "
echo " ██       ████   ██ ██    ██ ████  ████ ██      "
echo " ██   ███ ██ ██  ██ ██    ██ ██ ████ ██ █████   "
echo " ██    ██ ██  ██ ██ ██    ██ ██  ██  ██ ██      "
echo "  ██████  ██   ████  ██████  ██      ██ ███████ "                                                                                            
echo "#################################################################"
echo "build-latest: 0.1.0"
echo "opti-gnome-wayland-github: https://github.com/manoel-linux/opti-gnome-wayland"
echo "#################################################################"

if [[ $EUID -eq 0 ]]; then
echo "This script should not be executed as a superuser."
echo "Please run it without superuser privileges."
echo "#################################################################"
exit 1
fi

read -p "This action may have unintended consequences. Are you sure you want to continue? (y/n): " second_confirm
echo "#################################################################"
if [[ "$second_confirm" == "y" || "$second_confirm" == "Y" ]]; then
read -p "WARNING: This script is provided 'AS IS', without any warranties of any kind. The user assumes full responsibility for executing this script and any resulting consequences. We recommend backing up your data before proceeding. If the script does not cause any apparent issues, you can use the PC normally. Are you sure you want to proceed? (y/n): " third_confirm
echo "#################################################################"
if [[ "$third_confirm" == "y" || "$third_confirm" == "Y" ]]; then
echo "Proceeding with the changes..."
echo "#################################################################"
else
echo "Action canceled by the user."
echo "#################################################################"
exit 1
fi
else
echo "Action canceled by the user."
echo "#################################################################"
exit 1
fi


sudo gsettings set org.gnome.mutter attach-modal-dialogs false
sudo gsettings set org.gnome.mutter center-new-windows false
sudo gsettings set org.gnome.mutter edge-tiling false
sudo gsettings set org.gnome.mutter no-tab-popup false
sudo gsettings set org.gnome.desktop.interface can-change-accels false
sudo gsettings set org.gnome.desktop.interface clock-show-date false
sudo gsettings set org.gnome.desktop.interface clock-show-seconds false
sudo gsettings set org.gnome.desktop.interface clock-show-weekday false
sudo gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
sudo gsettings set org.gnome.desktop.interface cursor-blink false
sudo gsettings set org.gnome.desktop.interface enable-animations false
sudo gsettings set org.gnome.desktop.interface enable-hot-corners false
sudo gsettings set org.gnome.desktop.interface font-antialiasing 'none'
sudo gsettings set org.gnome.desktop.interface font-hinting 'none'
sudo gsettings set org.gnome.desktop.interface gtk-enable-primary-paste false
sudo gsettings set org.gnome.desktop.interface locate-pointer false
sudo gsettings set org.gnome.desktop.interface menubar-detachable false
sudo gsettings set org.gnome.desktop.interface menus-have-tearoff false
sudo gsettings set org.gnome.desktop.interface overlay-scrolling false
sudo gsettings set org.gnome.desktop.interface show-battery-percentage false
sudo gsettings set org.gnome.desktop.interface toolbar-detachable false
sudo gsettings set org.gnome.desktop.interface toolkit-accessibility false
sudo gsettings set org.gnome.desktop.notifications show-banners false
sudo gsettings set org.gnome.desktop.notifications show-in-lock-screen false
sudo gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true
sudo gsettings set org.gnome.desktop.sound event-sounds false
sudo gsettings set org.gnome.desktop.sound input-feedback-sounds false
sudo gsettings set org.gnome.desktop.background show-desktop-icons false
sudo gsettings set org.gnome.desktop.thumbnailers disable-all true
sudo gsettings set org.gnome.shell always-show-log-out false
sudo gsettings set org.gnome.shell disable-extension-version-validation false
sudo gsettings set org.gnome.shell remember-mount-password false
sudo gsettings set org.gnome.desktop.wm.preferences audible-bell false
sudo gsettings set org.gnome.desktop.wm.preferences auto-raise false
sudo gsettings set org.gnome.desktop.wm.preferences disable-workarounds false
sudo gsettings set org.gnome.desktop.wm.preferences raise-on-click false
sudo gsettings set org.gnome.desktop.wm.preferences resize-with-right-button false
sudo gsettings set org.gnome.desktop.wm.preferences titlebar-uses-system-font false
sudo gsettings set org.gnome.desktop.wm.preferences visual-bell false

gsettings set org.gnome.mutter attach-modal-dialogs false
gsettings set org.gnome.mutter center-new-windows false
gsettings set org.gnome.mutter edge-tiling false
gsettings set org.gnome.mutter no-tab-popup false
gsettings set org.gnome.desktop.interface can-change-accels false
gsettings set org.gnome.desktop.interface clock-show-date false
gsettings set org.gnome.desktop.interface clock-show-seconds false
gsettings set org.gnome.desktop.interface clock-show-weekday false
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface cursor-blink false
gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.interface enable-hot-corners false
gsettings set org.gnome.desktop.interface font-antialiasing 'none'
gsettings set org.gnome.desktop.interface font-hinting 'none'
gsettings set org.gnome.desktop.interface gtk-enable-primary-paste false
gsettings set org.gnome.desktop.interface locate-pointer false
gsettings set org.gnome.desktop.interface menubar-detachable false
gsettings set org.gnome.desktop.interface menus-have-tearoff false
gsettings set org.gnome.desktop.interface overlay-scrolling false
gsettings set org.gnome.desktop.interface show-battery-percentage false
gsettings set org.gnome.desktop.interface toolbar-detachable false
gsettings set org.gnome.desktop.interface toolkit-accessibility false
gsettings set org.gnome.desktop.notifications show-banners false
gsettings set org.gnome.desktop.notifications show-in-lock-screen false
gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true
gsettings set org.gnome.desktop.sound event-sounds false
gsettings set org.gnome.desktop.sound input-feedback-sounds false
gsettings set org.gnome.desktop.background show-desktop-icons false
gsettings set org.gnome.desktop.thumbnailers disable-all true
gsettings set org.gnome.shell always-show-log-out false
gsettings set org.gnome.shell disable-extension-version-validation false
gsettings set org.gnome.shell remember-mount-password false
gsettings set org.gnome.desktop.wm.preferences audible-bell false
gsettings set org.gnome.desktop.wm.preferences auto-raise false
gsettings set org.gnome.desktop.wm.preferences disable-workarounds false
gsettings set org.gnome.desktop.wm.preferences raise-on-click false
gsettings set org.gnome.desktop.wm.preferences resize-with-right-button false
gsettings set org.gnome.desktop.wm.preferences titlebar-uses-system-font false
gsettings set org.gnome.desktop.wm.preferences visual-bell false

sudo sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop

system_autostart_dir="/etc/xdg/autostart/"
user_autostart_dir="$HOME/.config/autostart/"

keep_the_files=(
    "org.gnome.SettingsDaemon.XSettings.desktop"
    "org.gnome.SettingsDaemon.A11ySettings.desktop"
    "org.gnome.SettingsDaemon.Color.desktop"
    "org.gnome.SettingsDaemon.Datetime.desktop"
    "org.gnome.SettingsDaemon.Housekeeping.desktop"
    "org.gnome.SettingsDaemon.Keyboard.desktop"
    "org.gnome.SettingsDaemon.MediaKeys.desktop"
    "org.gnome.SettingsDaemon.Power.desktop"
    "org.gnome.SettingsDaemon.PrintNotifications.desktop"
    "org.gnome.SettingsDaemon.Rfkill.desktop"
    "org.gnome.SettingsDaemon.ScreensaverProxy.desktop"
    "org.gnome.SettingsDaemon.Sharing.desktop"
    "org.gnome.SettingsDaemon.Smartcard.desktop"
    "org.gnome.SettingsDaemon.Sound.desktop"
    "org.gnome.SettingsDaemon.UsbProtection.desktop"
    "org.gnome.SettingsDaemon.Wacom.desktop"
    "org.gnome.SettingsDaemon.Wwan.desktop"
)

keep_the_files_home=(
    "ignore-lid-switch-tweak.desktop"
)

for file in $system_autostart_dir*; do
    if [[ ! " ${keep_the_files[@]} " =~ " ${file##*/} " ]]; then
        sudo rm "$file"
    fi
done

for file in $user_autostart_dir*; do
    if [[ ! " ${keep_the_files_home[@]} " =~ " ${file##*/} " ]]; then
        rm "$file"
    fi
done

echo "Maintained files in system autostart directory"
echo "#################################################################"
for file in "${keep_the_files[@]}"; do
    echo "$file"
done
echo "#################################################################"

echo "Maintained files in user autostart directory"
echo "#################################################################"
for file in "${keep_the_files_home[@]}"; do
    echo "$file"
done
echo "#################################################################"  
echo "DONE! Optimized GNOME"
echo "#################################################################"  
read -p "To apply the changes, you need to restart system. (y/n): " confirm
                
if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
echo "#################################################################"
echo "Restarting the system..."    
echo "#################################################################"
sudo reboot
else
echo "#################################################################"
echo "Restart canceled."
echo "#################################################################"
fi
