#!/bin/bash

if [[ "$XDG_SESSION_TYPE" != "wayland" ]]; then
echo "This script can only be executed in a Wayland environment."
exit 1
fi

if ! command -v dbus-daemon &> /dev/null; then
echo "#################################################################"
echo "ERROR: This script requires DBus to be executed."
echo "Make sure you have DBus installed on your system."
echo "DBus is required for inter-process communication."
echo "#################################################################"
exit 1
fi

clear
echo "#################################################################"
echo "opti-gnome-wayland-installer: june 2023"
echo "#################################################################"
echo "  ██████  ███    ██  ██████  ███    ███ ███████ "
echo " ██       ████   ██ ██    ██ ████  ████ ██      "
echo " ██   ███ ██ ██  ██ ██    ██ ██ ████ ██ █████   "
echo " ██    ██ ██  ██ ██ ██    ██ ██  ██  ██ ██      "
echo "  ██████  ██   ████  ██████  ██      ██ ███████ "                                                                                            
echo "#################################################################"
echo "build-latest: 0.0.3"
echo "opti-gnome-wayland-github: https://github.com/manoel-linux/opti-gnome-wayland"
echo "#################################################################"
echo "$(date)"
echo "Linux $(uname -r)"
echo "#################################################################"

if [[ $EUID -eq 0 ]]; then
echo "This script should not be executed as a superuser."
echo "Please run it without superuser privileges."
echo "#################################################################"
exit 1
fi

sudo gsettings set org.gnome.desktop.interface enable-animations false
sudo gsettings set org.gnome.desktop.background show-desktop-icons false
sudo gsettings set org.gnome.desktop.thumbnailers disable-all true
sudo gsettings set org.gnome.shell disable-user-extensions true

gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.background show-desktop-icons false
gsettings set org.gnome.desktop.thumbnailers disable-all true
gsettings set org.gnome.shell disable-user-extensions true

sudo sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop

directors="/etc/xdg/autostart/"

keep_the_files=(
    "org.gnome.SettingsDaemon.XSettings.desktop"
    "org.gnome.SettingsDaemon.A11ySettings.desktop"
    "org.gnome.SettingsDaemon.Color.desktop"
    "org.gnome.SettingsDaemon.Datetime.desktop"
    "org.gnome.SettingsDaemon.Housekeeping.desktop"
    "org.gnome.SettingsDaemon.Keyboard.desktop"
    "org.gnome.SettingsDaemon.MediaKeys.desktop"
    "org.gnome.SettingsDaemon.Power.desktop"
    "org.gnome.SettingsDaemon.PrintNotifications.desktop"
    "org.gnome.SettingsDaemon.Rfkill.desktop"
    "org.gnome.SettingsDaemon.ScreensaverProxy.desktop"
    "org.gnome.SettingsDaemon.Sharing.desktop"
    "org.gnome.SettingsDaemon.Smartcard.desktop"
    "org.gnome.SettingsDaemon.Sound.desktop"
    "org.gnome.SettingsDaemon.UsbProtection.desktop"
    "org.gnome.SettingsDaemon.Wacom.desktop"
    "org.gnome.SettingsDaemon.Wwan.desktop"
)

for files in $directors*; do
    if [[ ! " ${keep_the_files[@]} " =~ " ${files##*/} " ]]; then
        sudo rm $files
    fi
done

echo "maintained file"
echo "#################################################################"  
for files in "${keep_the_files[@]}"
do
    echo "$files"
done
echo "#################################################################"  
echo "DONE! Optimized GNOME"
echo "#################################################################"  
read -p "To apply the changes, you need to restart system. (y/n): " confirm

if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
echo "#################################################################"
echo "Restarting the system..."    
echo "#################################################################"
sudo reboot
else
echo "#################################################################"
echo "Restart canceled."
echo "#################################################################"
fi
